############
# COULEURS #
############

COUL_RESERVATION_IMPAYEE = "red3"
COUL_RESERVATION_PAYEE = "SeaGreen3"
COUL_FOND_CAL = "Grey95"
COUL_JOURS_CAL = "LightPink"
COUL_CHAMBRES_CAL = "LightSkyblue1"
COUL_BOUTTONS_NAVIGATION = "plum1"
COUL_CADENAS_OUVERT = "green"
COUL_CADENAS_FERME = "red3"
COUL_BOUTON_INFOS = COUL_BOUTTONS_NAVIGATION
COUL_BOUTTONS_AJOUTER = "PaleGreen"

############
# POLICE #
############

POLICE_JOURS = 'Verdana'
POLICE_JOURS_TAILLE = 12
COUL_POLICE_JOURS = "black"
POLICE_CHAMBRES = 'Arial'
POLICE_CHAMBRES_TAILLE = 16
COUL_POLICE_CHAMBRES = "black"
POLICE_DATA = 'Verdana'
POLICE_DATA_TAILLE = 12
COUL_POLICE_DATA = "black"
POLICE_BOUTONS = 'Verdana'
POLICE_BOUTONS_TAILLE = 12
COUL_POLICE_BOUTONS = "black"
POLICE_COMBOBOX = 'Verdana'
POLICE_COMBOBOX_TAILLE = 16
COUL_POLICE_COMBOBOX = "black"
POLICE_CHAMPS = 'Verdana'
POLICE_CHAMPS_TAILLE = 12
COUL_POLICE_CHAMPS = "black"