############
# COULEURS #
############

COUL_RESERVATION_IMPAYEE = "#ea9999"
COUL_RESERVATION_PAYEE = "#b6d7a8"
COUL_FOND_CAL = "Grey95"
COUL_JOURS_CAL = "#efc752"
COUL_CHAMBRES_CAL = "#efc752"
COUL_BOUTTONS_NAVIGATION = "#c1905e"
COUL_CADENAS_OUVERT = "green"
COUL_CADENAS_FERME = "red3"
COUL_BOUTON_INFOS = "#c1905e"
COUL_BOUTTONS_AJOUTER = "#c1905e"
COUL_BORDS_RESA_CLASSIQUE = "grey"
COUL_BORDS_RESA_BOOKING = "cornflower blue"
COUL_TRAITS_RESA = "grey30"
COUL_BORDS_RESA_HB = "#efc752"

############
# POLICE #
############

POLICE_JOURS = 'Verdana'
POLICE_JOURS_TAILLE = 12
COUL_POLICE_JOURS = "black"
POLICE_CHAMBRES = 'Arial'
POLICE_CHAMBRES_TAILLE = 16
COUL_POLICE_CHAMBRES = "black"
POLICE_DATA = 'Verdana'
POLICE_DATA_TAILLE = 12
COUL_POLICE_DATA = "black"
POLICE_BOUTONS = 'Verdana'
POLICE_BOUTONS_TAILLE = 12
COUL_POLICE_BOUTONS = "black"
POLICE_COMBOBOX = 'Verdana'
POLICE_COMBOBOX_TAILLE = 16
COUL_POLICE_COMBOBOX = "black"
POLICE_CHAMPS = 'Verdana'
POLICE_CHAMPS_TAILLE = 12
COUL_POLICE_CHAMPS = "black"